---
title: "02-modeling"
author: "YANKAI MA"
date: "2026-07-22"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Data Preparation

```{r}

df <- read_csv(
  "data/cleaned_panel_2021_2025.csv",
  col_types = cols(city_code = col_character(), .default = col_guess()),
  show_col_types = FALSE
)
ncol_bldg <- ncol(df) - 6
colnames(df)[4:ncol_bldg] <- c(
  "all_type_building_count_total",
  "all_type_building_area",
  "living_count",
  "living_area",
  "dormitory_count",
  "dormitory_area",
  "mixed_use_count",
  "mixed_use_area",
  "agri_count",
  "agri_area",
  "mining_count",
  "mining_area",
  "plant_count",
  "plant_area",
  "energy_count",
  "energy_area",
  "it_count",
  "it_area",
  "logis_count",
  "logis_area",
  "retail_count",
  "retail_area",
  "finance_count",
  "finance_area",
  "real_estate_count",
  "real_estate_area",
  "hotel_count",
  "hotel_area",
  "education_count",
  "education_area",
  "health_count",
  "health_area",
  "other_service_count",
  "other_service_area",
  "official_count",
  "official_area",
  "other_type_count",
  "other_type_area"
)


# Percentage of total area accounted for by the 18 subcategories p
df_prop <- df %>%
  filter(all_type_building_area > 0) %>%            # Drop all zero rows
  mutate(
    across(
      ends_with("_area") & !all_type_building_area,
      ~ .x / all_type_building_area,
      .names = "p_{.col}"
    )
  ) %>%
  rename_with( ~ str_remove(., "_area$"), starts_with("p_"))

# Proportions of the 17 subcategories (excluding p_living) 
fine_cols <- setdiff(grep("^p_", names(df_prop), value = TRUE), "p_living")

# 70/30 Split train and test set
set.seed(1)
idx <- sample(nrow(df_prop), 0.7 * nrow(df_prop))
df_train <- df_prop[idx, ]
df_test  <- df_prop[-idx, ]

```
